### ISSUE TITLE
Why reviewable.io for code reviews?

### ISSUE THREAD

**Issue by asbjornu** [HydraCG/Specifications#135]
The comment by @elf-pavlik in https://github.com/HydraCG/Specifications/pull/132#issuecomment-322179489, took me to the following statement by @lanthaler:

> it's currently difficult to keep track what has been addressed and what hasn't

I realise I don't have much to say on this as I haven't phoned in on the Hydra conference calls, but I'm not sure I understand this argument.

There's quite extensive review support in GitHub and I haven't seen any of it put to use in this repository. What's missing on GitHub.com, specifically? Filtering based on review status is quite extensive, for instance:

![GitHub Review Status](https://user-images.githubusercontent.com/12283/29313022-f8a0ea04-81b7-11e7-8ae4-3749d34cdf68.png)

It's also easy to ask for reviews, see who's reviewing a particular PR and their individual review status:

![GitHub Reviewers](https://user-images.githubusercontent.com/12283/29313050-21084596-81b8-11e7-9bb7-c71402a8b8eb.png)

With the built-in review system, it's also possible to block merging before the review has been passed, for instance:

![screen shot 2017-08-15 at 12 50 18](https://user-images.githubusercontent.com/12283/29313100-61464a2c-81b8-11e7-8186-6ecf0ea72602.png)

There are so many upsides to using the built-in code-review of GitHub that I don't quite understand the choice to use Reviewable. Can someone please explain them to me? 😃

**Comment by akuckartz** [comment]
:+1:

**Comment by lanthaler** [comment]
My main issue is that I don't see easily what has been changed between reviews and whether the comments have been addressed or not. In Reviewable it's pretty easy to follow along:

![image](https://user-images.githubusercontent.com/456407/29332835-b8efe014-8201-11e7-86de-c0bba34bfef8.png)

I can mark individual comments as blocking or resolved etc. and can also easily just look at files that have changed since I last reviewed a PR.

**Comment by tpluscode** [comment]
I think I was undecided before, but indeed it's quite productive. Every time you visit you get to react to any new stuff and not waste time scrolling back and forth through tons of comments

**Comment by asbjornu** [comment]
Ok, I see. The functionality around individual comments is more limited on GitHub, I agree. But whenever a comment about the code is addressed by a new commit, GitHub will mark the comment "outdated" and collapse it. I find that functionality and a lot else to be better than Reviewable.

**Comment by lanthaler** [comment]
> But whenever a comment about the code is addressed by a new commit, GitHub will mark the comment "outdated" and collapse it.

Yeah, but you can't track what happened with it. I kept scrolling back and forth and after I few rounds of reviews and comments by different people I usually completely lost track of where we stand.

I'd love if GitHub would integrate some of Reviewable's functionality. So far it's still missing some really important features which is why I strongly prefer Reviewable as it makes me much more efficient. Maybe give it a chance and try to weigh in on a few PRs over a few cycles. Perhaps you start to like it too :-)

**Comment by asbjornu** [comment]
Sure, I'll try it out. Thanks for the explanation!
